LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE:= mousebot
LOCAL_SRC_FILES := mousebot.cc
LOCAL_C_INCLUDES := 
LOCAL_LDLIBS :=
LOCAL_CFLAGS= 
LOCAL_ALLOW_UNDEFINED_SYMBOLS := true
LOCAL_SHARED_LIBRARIES =
include $(BUILD_SHARED_LIBRARY)

